aica-technology/network-interfaces

cpp/include/network_interfaces/zmq/exceptions/InvalidControlTypeVectorException.h
cpp/include/network_interfaces/zmq/exceptions/UnknownControlTypeException.h

Sorry guys, the exceptions somehow got lost because of some git commands...

Hotfix: add exceptions headers

---

cpp/include/network_interfaces/control_type.h
cpp/include/network_interfaces/zmq/network.h

Include ostream

---

Dockerfile
README.md
install.sh

Apart from updating the README here, I'm adding an installation script for the network interfaces. I already checked that it works with hardware interfaces and other repositories. I did not include the control libraries installation here though, it's required to do that before the installation of network interfaces

Installation script

---

cpp/include/network_interfaces/zmq/network.h
cpp/scripts/zmq_loopback_command.cpp
cpp/scripts/zmq_loopback_state.cpp

Fix includes due to changes in control libraries

---

CHANGELOG.md
Dockerfile
README.md
build-test.sh
cpp/CMakeLists.txt
cpp/include/network_interfaces/zmq/network.h
cpp/scripts/zmq_loopback_command.cpp
cpp/scripts/zmq_loopback_state.cpp
dev-server.sh
install.sh
python/setup.py

Following the release of control libraries, the release here for network interfaces using the 5.0.0 tag
@buschbapti

Release 1.0.0

---

.github/workflows/manual-dispatch.yml
CHANGELOG.md
Dockerfile
build-test.sh
cpp/CMakeLists.txt
cpp/Config.cmake.in
dev-server.sh
python/network_interfaces/zmq/network.py
python/setup.py
python/test/test_zmq_communication.py

After the small changes from PR #15, I'd like to do merge these changes into main and create a new release 1.1 (changes were not breaking).
If you agree, I would also delete develop branch and feature branches can be created from main directly.

Release 1.1.0

---

Dockerfile
README.md
build-test.sh
cpp/include/network_interfaces/zmq/network.h
cpp/test/test_zmq_communication.cpp
dev-server.sh
install.sh
python/test/test_zmq_communication.py

- No parent issue, maintenance PR
Wow, network interfaces was still using the LASA repo. About time to change that. The backend doesn't build without this fix due to the clproto header
Estimated Time of Review: 5 minutes

Use develop branch of aica-technology/control-librares

---

cpp/CMakeLists.txt
python/setup.py

Need to update develop here and then I think it's best to make a new release here. Needed for hardware-interfaces
Estimated Time of Review: 2 minutes

Use control libraries version 7.0

---

CHANGELOG.md
Dockerfile
README.md
build-test.sh
cpp/CMakeLists.txt
cpp/include/network_interfaces/zmq/network.h
cpp/test/test_zmq_communication.cpp
dev-server.sh
install.sh
python/setup.py
python/test/test_zmq_communication.py

After updating to control libraries 7.0, let's make a new release here as well. As before, I will merge with merge commit and then recreate the develop branch from main.
Estimated Time of Review: 5 minutes

Release 1.2.0

---

source/Dockerfile
source/README.md
source/communication_interfaces/CMakeLists.txt
source/communication_interfaces/include/communication_interfaces/ByteArray.hpp
source/communication_interfaces/include/communication_interfaces/sockets/ISocket.hpp
source/communication_interfaces/src/ByteArray.cpp
source/communication_interfaces/test/test_communication_interfaces.cpp
source/communication_interfaces/test/tests/test_byte_array.cpp
source/dev-server.sh
source/install.sh

- #24 
Please read the issue and epic first. I would like to start this project. Big PR but most is coming from project files and bash scripts.
In terms of code, I think you will already be able to tell where I'm going with this. If you can already see problems with this approach or if you don't like names, let me know. There is also [this branch](https://github.com/aica-technology/network-interfaces/tree/feature/sockets) where I already implemented and tested ZMQ and UDP sockets.
Estimated Time of Review: 30 minutes
Review by commit

Add ISocket class in communication interfaces

---

source/communication_interfaces/CMakeLists.txt
source/communication_interfaces/include/communication_interfaces/exceptions/SocketConfigurationException.hpp
source/communication_interfaces/include/communication_interfaces/sockets/ISocket.hpp
source/communication_interfaces/include/communication_interfaces/sockets/UDPClient.hpp
source/communication_interfaces/include/communication_interfaces/sockets/UDPServer.hpp
source/communication_interfaces/include/communication_interfaces/sockets/UDPSocket.hpp
source/communication_interfaces/src/sockets/UDPClient.cpp
source/communication_interfaces/src/sockets/UDPServer.cpp
source/communication_interfaces/src/sockets/UDPSocket.cpp
source/communication_interfaces/test/tests/test_udp_communication.cpp

- #26 
That's a rather big PR, sorry for that, but most lines are coming from header files. The interesting stuff happens in UDPSocket.cpp and in the test file.
This has been tested with the [test/comm-interfaces](https://github.com/aica-technology/hardware-interfaces/tree/test/comm-interfaces) branch on hardware interfaces and the communication with the kuka rsi simulation still works as expected.
Estimated Time of Review: 20 minutes

Add UDP server and client classes

---

source/communication_interfaces/CMakeLists.txt
source/communication_interfaces/communication_interfaces-config.cmake.in
source/communication_interfaces/communication_interfaces.pc.in
source/install.sh

- #32 
I reused some code here from network interfaces (the old package) and control libraries. Tested with hardware interfaces.
Estimated Time of Review: 15 minutes

Add pkg-config files

---

source/communication_interfaces/CMakeLists.txt
source/communication_interfaces/include/communication_interfaces/sockets/ZMQPublisherSubscriber.hpp
source/communication_interfaces/include/communication_interfaces/sockets/ZMQSocket.hpp
source/communication_interfaces/src/sockets/ZMQPublisherSubscriber.cpp
source/communication_interfaces/test/tests/test_zmq_communication.cpp

- #31 
This PR solves the issue by combining a ZMQ publisher and subscriber into one class that can both send and receive data.
Estimated Time of Review: 15 minutes

Abstract ZMQ publisher and subscriber into one class

---

source/communication_interfaces/CMakeLists.txt
source/communication_interfaces/communication_interfaces-config.cmake.in

- #46 
This PR solves the issue by adding the necessary cmake directives to the CMakeLists. Thanks @LouisBrunner for looking into that!
Estimated Time of Review: 5 minutes

Fix CMakeLists with correct linking and install

---

.github/workflows/build-release.yaml

- aica-technology/.github#20
Estimated Time of Review: 0.5 minutes

Update docker-tag-from-git version

---

.github/workflows/build-release.yaml

Fixes #51 (see https://github.com/aica-technology/network-interfaces/actions/runs/5643871392)
Because we have multiple tags sometimes (e.g. `main-23` and `v1.4.0`), we can't do string interpolations on tags. Instead we should use an action which can manipulate list, so instead of doing `${{ needs.get-tag.outputs.tag }}-${{ matrix.arch }}` (which would give you `main-23,v1.4.0-amd64`) you use `aica-technology/.github/.github/actions/list-add-suffixes` (which would give you `main-23-amd64,v1.4.0-amd64`).
Estimated Time of Review: 2 minutes

fix(ci): upgrade .github to v0.6.1 and do proper tags merging

---

.github/workflows/build-release.yaml
CHANGELOG.md
Dockerfile.ci
cpp/CMakeLists.txt
python/setup.py
source/communication_interfaces/CMakeLists.txt

Release develop with the two fixes that are quite useful.
Estimated Time of Review: 2 minutes

Release Version 1.4.1

---

Dockerfile

- #47 
Same PR as https://github.com/aica-technology/control-libraries/pull/135.
Estimated Time of Review: 5 minutes

feat(python): add stage to generate python stubs

---

CHANGELOG.md
python/setup.py
source/communication_interfaces/CMakeLists.txt

This completes the recent push on this repository.
Estimated Time of Review: 3 minutes

release: version 2.0.0 (communication interfaces 1.0.0)

---

CHANGELOG.md
Dockerfile
build.sh

- https://github.com/aica-technology/backend/issues/153
All libraries should be available under `/usr` and not `/usr/local`
Estimated Time of Review: 2 minutes

fix(build): copy library to /usr
